# overrides for local development, not used in CI
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: perma_web/Dockerfile
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/perma-web:89-b3f7654c564e8725458a90c842f1b7cd
        platforms:
          - linux/amd64
          - linux/arm64
      x-hash-paths:
        - perma_web/requirements.txt
        - perma_web/npm-shrinkwrap.json
        - perma_web/package.json
        - perma_web/perma-warcprox-ca.pem
        - perma_web/lil-archive-keyring.gpg

  wacz-exhibitor:
    build:
      context: ./services/docker/wacz-exhibitor
      args:
        RELEASE: v0.1.7
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/wacz-exhibitor:4-a5e9864366f88b9024d03d66e60f6a2b
        platforms:
          - linux/amd64
          - linux/arm64
      x-hash-paths:
        - ./nginx.conf

  #
  # Scoop REST API
  #
  scoop-db:
    image: registry.lil.tools/library/mariadb:10.6.14
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=scoop_api
    volumes:
      # If the volume contains a database (a subdirectory named mysql)
      # when you start the container, it will be left untouched and unaffected
      # by config environment variables like $MARIADB_ROOT_PASSWORD.
      - scoop_db_data:/var/lib/mysql:delegated
    networks:
      - scoop_rest_api_internal

  scoop-rest-api:
    image: registry.lil.tools/harvardlil/scoop-rest-api:33-966e4755f4a6abe5d88b8fd9f0405152
    init: true
    tty: true
    depends_on:
      - scoop-db
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - API_DOMAIN=http://scoop-rest-api:5000
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=scoop-db
      - DATABASE_PORT=3306
      - DATABASE_NAME=scoop_api
      - START_CRON=true                   # false|true
      - START_FLASK_SERVER=true           # false|true
      - START_CAPTURE_PROCESSES=parallel  # none|single|parallel
      - DISPLAY=:99                       # Run Xvfb with the below virtual display number
      - CREATE_ACCESS_KEY_WITH_LABEL=dev  # create a new access key each time the container starts
    volumes:
      - scoop_access_key:/app/docker/access_keys:delegated
      - ./services/docker/scoop-rest-api/config.py:/app/scoop_rest_api/config.py
    networks:
      - scoop_rest_api
      - scoop_rest_api_internal

  #
  # Perma Payments
  #
  pp_db:
    image: registry.lil.tools/library/postgres:12.8
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - pp_db_data:/var/lib/postgresql/data:delegated
    networks:
      - perma_payments

  perma-payments:
    image: registry.lil.tools/harvardlil/perma-payments:6-fc3e7a41c2c4ab7dd526cacb63a64e78
    # hack: sleep to give the database time to start up
    command: >
      sh -c "sleep 5 && ./manage.py migrate && invoke run"
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - pp_db
    environment:
      - DJANGO__DATABASES__default__HOST=pp_db
      - DOCKERIZED=true
    # TO CUSTOMIZE CONFIG:
    # copy ./services/docker/perma-payments/settings.py.example
    # to ./services/docker/perma-payments/settings.py,
    # alter config as desired, in the usual way, then comment in this volume
    # and re-run docker-compose up
    # volumes:
    #   - ./services/docker/perma-payments/settings.py:/app/web/config/settings/settings.py
    networks:
      - default
      - perma_payments
